site_name: Serveis en Xarxa CFGM
theme:
  name: readthedocs

nav: 
  - SERVEIS EN XARXA CFGM: index.md
  - 1. CONCEPTES SOBRE XARXES: u1-conceptes-xarxes.md
  -     1.1. Exercicis ipv4: exercicis-ipv4.md
  - 2. SERVEI FTP: u2-servei-ftp.md
  -     2.1 Preguntes exemple: preguntes-test.md
  -     2.2 Instal.lació vsFTPd: u2-ftp-vsftpd.md
  -     2.3 Preguntes test: u2-test-preguntes.md
  - 3. SERVEI HTTP: u3-servei-http.md
  - 4. SCRIPTING: u4-Scripting.md
  - Errors Comuns Apache: errors-comuns.md
  - (provaVue): provaVue.md
